GET http://localhost:3000/boats

###

POST http://localhost:3000/boats
content-type: application/json

{
  "price": 100,
  "topSpeedInKnots": 20,
  "capacity": 10,
  "name": "second boat!"
}


###

PATCH http://localhost:3000/boats/rent/0e6c911f-fe34-4fcf-869a-f0e15eccc258

###

PATCH http://localhost:3000/boats/return/0e6c911f-fe34-4fcf-869a-f0e15eccc258
